### ISSUE TITLE
How do you plan to make submissions?

### ISSUE THREAD

**Issue by weeebdev** [dianhsu-official/ccs#1]
Currently, I have a setup that involves Competitest.nvim. I wanted to ask if your cli is intended to do the same or if you plan to add submissions as well.

**Comment by dianhsu** [comment]
Due to new situation, **ccs** can allow you to code with multiple platform, it's hard to adapted all platforms. But for submission, I think  submit by copy and paste code is enough. For codeforces, I think I can write a small web script to submit code at problem detail page.

**Comment by weeebdev** [comment]
I see, thanks
